#!/usr/bin/env bash
# Install nginx on your web-01
apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

ufw allow 'Nginx HTTP'

service nginx start
