#!/usr/bin/env bash
# This script manages the other mange script and dose some other things.
file="/var/run/my_process.pid"
process="manage_my_process"
startarg()
{
	if [ -f "$file" ]; then
		cat "$file"
	else
		./manage_my_process &
		echo "$!" > "$file"
		echo "manage_my_process started"
	fi
}
stoparg()
{
	kill "$(pgrep "$process")"
	rm "$file"
	echo "manage_my_process stopped"
}
restartarg()
{
	stoparg
	startarg
	echo "manage_my_process restarted"
}
case "$1" in
	start)
		startarg;;
	stop)
		stoparg;;
	restart)
		restartarg;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}";;
esac
