#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely
signal()
{
	echo "I am invincible!!!"
	exit 0
}
trap 'signal' SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
