#!/usr/bin/env bash
#This script  displays numbers from 1 to 100 but fizz for multiple of 3 and buzz for thos of 5 and fizzbuzz for multiples for both
i=1
while [ $i -le 100 ]; do
	if ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	elif ((i % 3 == 0 && i % 5 == 0)); then
		echo "FizzBuzz"
	else
		echo "$i"
	fi
	((i++))
done
