#!/usr/bin/env bash
# This script displays the comtent of the file /etc/passwd
file="/etc/passwd"
while IFS=: read -r username password userid groupid useridinfo homedir commandshell; do
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $commandshell. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < "$file"
